use std::collections::HashMap;


pub struct AlternativeTable<'a> {
    map: HashMap<&'a str, Vec<&'a str>>
}

impl AlternativeTable<'_> {
    pub fn new() -> Self {
        let mut the_map = HashMap::new();
        for line in MISPELLING_TABLE {
            let words = (*line).split(" ").into_iter().collect::<Vec<&str>>();
            let key = words[0];
            let alternatives = Vec::from_iter(words[1..].into_iter().map(|x| *x));
            the_map.insert(key, alternatives);
        }
        AlternativeTable { map: the_map }
    }

    pub fn alternatives(&self, s: &str) -> Option<&Vec<&str>> {
        self.map.get(s)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn it_works() {
        let gen = AlternativeTable::new();
        let x = gen.alternatives("able").unwrap();
        assert_eq!(x.len(), 2);
        assert_eq!(x[0], "cable");
        assert_eq!(x[1], "table");
    }
}

static MISPELLING_TABLE: &'static [&str] = &[
    "able cable table",
    "across cross",
    "act art cat pact",
    "action auction",
    "add dad",
    "again gain",
    "age cage page wage",
    "ahead head",
    "aim air arm",
    "air hair pair",
    "all ball call fall ill wall",
    "alley valley",
    "alter later",
    "anger danger",
    "angle ankle",
    "arch march",
    "area arena",
    "arm army art farm warm",
    "around round",
    "arrow narrow",
    "art cart",
    "ask mask task",
    "aunt hunt",
    "avoid void",
    "awake aware",
    "away way",
    "bag bar tag",
    "ball call fall wall",
    "bar car jar",
    "base case",
    "battle cattle",
    "beach bench teach",
    "bean mean",
    "belt best melt",
    "best nest test west",
    "better bitter butter letter",
    "bid bind bird kid",
    "bike like",
    "bind bird blind find kind mind",
    "bitter butter",
    "blade blame",
    "blame flame",
    "blue blur glue",
    "blush brush flush slush",
    "boat goat",
    "body boy",
    "boil coil foil oil",
    "bone one tone zone",
    "book cook",
    "border order",
    "boring bring",
    "boss toss",
    "box boy fox",
    "boy joy toy",
    "brain grain rain train",
    "brass grass",
    "brick brisk trick",
    "bridge ridge",
    "brief grief",
    "bright right",
    "bring ring",
    "brisk risk",
    "broom room",
    "brown frown",
    "brush crush",
    "bulb bulk",
    "bus busy",
    "cable table",
    "cage cake case cave page wage",
    "cake case cave lake make",
    "call calm fall wall",
    "calm palm",
    "camp damp lamp ramp",
    "can car cat fan man scan van",
    "cannon canyon",
    "car card cart cat jar",
    "card cart hard yard",
    "cart cat",
    "case cash cause cave chase",
    "cash crash dash wash",
    "castle cattle",
    "cat chat fat hat",
    "catch match patch",
    "cause pause",
    "cave have pave save wave",
    "certain curtain",
    "chair hair",
    "change charge",
    "chat hat that what",
    "chef chief",
    "clap claw clay clip",
    "claw clay law",
    "clay play day",
    "click clock",
    "climb limb",
    "clip flip",
    "clock flock lock",
    "clog dog",
    "cloud loud",
    "clutch dutch",
    "coach couch",
    "coast cost roast toast",
    "code come core",
    "coil coin cool foil oil",
    "coin corn join",
    "come core home",
    "cook cool",
    "cool pool tool wool",
    "coral moral",
    "core corn more",
    "corn horn",
    "cost host post",
    "couch crouch",
    "cover hover over",
    "crack rack track",
    "craft draft",
    "cram cream",
    "crash crush trash",
    "cream dream",
    "crop drop",
    "cry dry try",
    "cube cute tube",
    "dad day mad sad",
    "damp lamp ramp",
    "daring during",
    "dash dish wash",
    "dawn lawn",
    "day dry say way",
    "deal dial real",
    "decade decide",
    "defy deny",
    "derive drive",
    "dice ice nice rice",
    "diet dirt",
    "dinner inner winner",
    "dish fish wish",
    "dog fog clog",
    "donkey monkey",
    "donor door",
    "door odor",
    "dose dove nose rose close",
    "dove love move",
    "draft drift",
    "draw raw",
    "drip drop trip",
    "dry try",
    "dust just must",
    "earn learn",
    "east easy vast",
    "edit exit",
    "eight height light night right sight",
    "either neither",
    "emerge merge",
    "emotion motion",
    "enable unable",
    "enact exact",
    "end lend",
    "estate state",
    "exist exit",
    "face fade fame race",
    "fade fame",
    "fall wall",
    "fame flame frame game name same",
    "fan fat fun man van",
    "farm firm warm",
    "fat fit flat hat",
    "father gather rather",
    "fault vault",
    "fee feed feel few flee",
    "feed feel need seed",
    "feel fuel",
    "fever never",
    "file film fine fire",
    "film firm",
    "find fine kind mind",
    "fine fire wine",
    "finger ginger",
    "fire firm hire wire",
    "fish wish",
    "fit fix kit",
    "fitness witness",
    "fix fox mix six",
    "flag flat",
    "flame frame",
    "flash flush",
    "flat float",
    "flight light slight",
    "flock lock",
    "flush slush",
    "fog fox frog",
    "foil oil",
    "fold food gold hold old",
    "follow hollow",
    "food foot good hood wood",
    "fork work",
    "found round sound",
    "front frost",
    "fun gun run sun",
    "funny sunny",
    "gain grain main rain",
    "game gate gaze name same",
    "gap gas gasp",
    "garage garbage",
    "gas gasp",
    "gasp wasp",
    "gate gaze rate",
    "gather rather",
    "gaze maze",
    "ghost host",
    "giant grant",
    "gift lift",
    "give live",
    "glass grass",
    "glide guide slide",
    "globe glove",
    "glove love",
    "glow grow slow",
    "gold good hold old",
    "good hood wood",
    "gown own town",
    "grace grape race",
    "grain rain train",
    "grant grunt",
    "great treat",
    "grid grit",
    "gun run sun",
    "hair pair",
    "hand hard sand",
    "hard yard",
    "hat that what",
    "have pave save wave",
    "health wealth",
    "hen pen ten then when",
    "hero zero",
    "hill ill pill will",
    "hint hunt",
    "hip ship tip whip",
    "hire wire",
    "hold hole hood old",
    "hole home hope pole",
    "home hope",
    "hood wood",
    "host post",
    "hover over",
    "humble tumble",
    "hunt hurt",
    "ice nice rice",
    "icon iron",
    "ill pill will",
    "inject insect",
    "inner winner",
    "issue tissue",
    "item stem",
    "job joy",
    "joy toy",
    "just must",
    "keen keep",
    "kick sick",
    "kid kind kit",
    "kind mind",
    "kiss miss",
    "kit kite",
    "know now snow",
    "lab law slab",
    "lady lazy",
    "lake like make",
    "lamp ramp",
    "later layer water",
    "law lawn raw",
    "left lift",
    "lend lens",
    "life lift like live wife",
    "lift list",
    "light night right sight slight",
    "like live",
    "link pink wink",
    "live love olive",
    "load loan loud road",
    "local loyal vocal",
    "lock sock",
    "long song",
    "lottery pottery",
    "love move",
    "loyal royal",
    "lumber number",
    "lunch punch",
    "mad maid man sad",
    "maid mail main",
    "mail main rail sail tail",
    "main man rain",
    "make maze",
    "man mean van",
    "march match",
    "mask mass task",
    "mass miss pass",
    "master matter",
    "match math patch",
    "math myth path",
    "mean meat",
    "meat melt seat",
    "medal metal",
    "mercy merry",
    "milk silk",
    "mix six",
    "moon soon",
    "more move",
    "mother other",
    "move movie",
    "much such",
    "mule rule",
    "name same",
    "near pear wear year",
    "need seed",
    "nest net next test west",
    "net next nut pet wet",
    "next text",
    "nice rice",
    "night right sight",
    "noise nose",
    "north worth",
    "nose note rose",
    "note vote",
    "now snow",
    "nurse purse",
    "nut put",
    "once one",
    "one tone zone",
    "open oven pen",
    "orange range",
    "oven over",
    "own town",
    "ozone zone",
    "paddle saddle",
    "page pave wage",
    "palace place",
    "patch path pitch",
    "pave save wave",
    "peace place",
    "pear wear year",
    "pen pet ten",
    "pet poet put wet",
    "pill pull will",
    "pink wink",
    "place plate",
    "poem poet",
    "poet post",
    "point print",
    "polar solar",
    "pond pony",
    "pool tool wool",
    "powder power",
    "power tower",
    "praise raise",
    "present prevent",
    "price pride prize rice",
    "pride prize ride",
    "project protect",
    "proof roof",
    "pull pulp",
    "pulse purse",
    "quit quiz suit",
    "race rack rare rate rice",
    "rack track",
    "rail rain sail tail",
    "rain train",
    "rare rate",
    "reason season",
    "rent tent",
    "rice rich ride",
    "ride ridge rude side tide wide",
    "right sight",
    "ring sing wing",
    "roast toast",
    "roof room",
    "round sound",
    "rude rule",
    "rug run",
    "run sun",
    "sad sand say",
    "safe same save",
    "sail tail",
    "salmon salon",
    "same save",
    "sample simple",
    "sand stand",
    "save wave",
    "say shy spy stay way",
    "scale scare",
    "scare share spare",
    "sea seat",
    "seed seek shed speed",
    "sell shell spell tell",
    "shaft shift",
    "shallow swallow",
    "share spare",
    "shell spell",
    "shift swift",
    "ship shop whip",
    "shock sock stock",
    "shoe shop shove",
    "shoot short",
    "short sort sport",
    "shove stove",
    "shy spy",
    "sick silk sock stick",
    "side size slide tide wide",
    "sight slight",
    "sign sing",
    "sing song sting swing wing",
    "skate state",
    "ski skin",
    "skill skull still",
    "skin spin",
    "slab slam",
    "slam slim",
    "slice slide spice",
    "slim swim",
    "slot slow spot",
    "slow snow",
    "smart start",
    "snap soap swap",
    "soap soup swap",
    "sock stock",
    "soft sort",
    "soon spoon",
    "sorry worry",
    "sort sport",
    "soul soup",
    "south youth",
    "space spare spice",
    "speak steak",
    "speed spend",
    "spice spike",
    "sport spot",
    "stable table",
    "staff stuff",
    "stage state",
    "stamp swamp",
    "stem step",
    "stick stock",
    "sting swing",
    "stone stove tone",
    "stool tool",
    "stumble tumble",
    "sure surge",
    "surge urge",
    "swamp swap",
    "swarm warm",
    "swear wear",
    "swing wing",
    "sword word",
    "talk tank task walk",
    "tank task thank",
    "tape type",
    "taste waste",
    "team term",
    "ten tent then",
    "tent test text",
    "test text west",
    "that what",
    "theme there",
    "then they when",
    "there three where",
    "three tree",
    "tide time wide",
    "tip top trip",
    "toe tone top toy",
    "tone zone",
    "tool wool",
    "top toy",
    "toy try",
    "track trick truck",
    "trap tray trip wrap",
    "tray try",
    "tree true",
    "trick truck",
    "trim trip",
    "twin win",
    "use used",
    "verb very",
    "wage wave",
    "wait want",
    "walk wall",
    "wall will",
    "wash wasp wish",
    "wear year",
    "web wet",
    "west wet",
    "what wheat",
    "wide wife wine wire wise",
    "wife wine wire wise",
    "wild will",
    "win wine wing wink",
    "wine wing wink wire wise",
    "wing wink",
    "winner winter",
    "wire wise",
    "wise wish",
    "wood wool word",
    "word work world",
];
